### ISSUE TITLE
Responsive corrections

### ISSUE THREAD

**Issue by hansajith1998** [sublimemahesh/trades.lk#320]

**Comment by sublimemahesh** [comment]
Also please change the images paths of the businesses

Now there are only 2 files  for the business

1. logo (trades.lk/upload/business/logo/) - 400px*400px 
2. cover_image (trades.lk/upload/business/cover/) - 1000px*452px

Please change the necessary arrangements in the thought of the website

![image](https://user-images.githubusercontent.com/21656883/83336742-96cc6c00-a2d3-11ea-881e-548a476d5057.png)

![image](https://user-images.githubusercontent.com/21656883/83336777-d6935380-a2d3-11ea-8a4f-c79853856aa4.png)
